### ISSUE TITLE
line_col entered unreachable code when input has unicode

### ISSUE THREAD

**Issue by sunng87** [dragostis/pest#60] opened 2016-06-19 09:07 UTC
Pest 0.2.9

internal error: entered unreachable code', /home/nsun/.cargo/registry/src/crates.mirrors.ustc.edu.cn-e2f007c923a8536a/pest-0.2.9/src/inputs/string_input.rs:100

Minimal reproducible code 

```rust
    let src = "你好这是一段中文\n{{hello}}\n\t你好\n{{hello}}";
    let i2 = StringInput::new(src);
    let mut rdp = Rdp::new(StringInput::new(src));
    rdp.handlebars();

    for i in rdp.queue().iter() {
        println!("{:?}", i.rule);
        println!("{:?}", rdp.slice_input(i.start, i.end));
        println!("{:?}", i2.line_col(i.start));
        println!("----------------------------");
    }

```

Output

```
template
"\u{4f60}\u{597d}\u{8fd9}\u{662f}\u{4e00}\u{6bb5}\u{4e2d}\u{6587}\n{{hello}}\n\t\u{4f60}\u{597d}\n{{hello}}"
(1, 1)
----------------------------
raw_text
"\u{4f60}\u{597d}\u{8fd9}\u{662f}\u{4e00}\u{6bb5}\u{4e2d}\u{6587}\n"
(1, 1)
----------------------------
expression
"{{hello}}"
(4, 3)
----------------------------
identifier
"hello"
(4, 5)
----------------------------
raw_text
"\u{4f60}\u{597d}\n"
thread 'main' panicked at 'internal error: entered unreachable code', /home/nsun/.cargo/git/checkouts/pest-d495d899ac544743/master/src/inputs/string_input.rs:95

```

It seems the line_col function returns wrong result starts from `{{hello}}`, I guess there is some issue dealing with multi-byte character here.

**Comment by dragostis** [comment] 2016-06-19 11:42
I've found where the issue is caused, but I still have to see where the flaw lies. Thanks for reporting! 👍 

I'll try to see if I can fix all the issues for the `0.3.0` release today. If not, I'll get them fixed by Tuesday.

**Closed** 2016-06-22 21:44 UTC
Labels: bug
